[package]
name = "byte_marks"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
license = "AGPL-3.0-or-later"
description = "A rust lib crate to mark/unmark transmitted/received byte boundaries for messages."

[features]
std = []
default = ["std"]
[dependencies]
